/**
 * Mirror of `src/blogs/contracts/common.py`.
 *
 * This directory is the ONLY place backend field names appear. Nothing above
 * it re-declares a shape or inlines an endpoint path, so when a contract moves
 * the compiler points at every call site.
 *
 * Two properties of the Python side that constrain everything here:
 *
 *   `extra="forbid"` — an unknown key in a request body is a 400, never an
 *   ignored field. Request types are exact; do not spread loose objects into
 *   them.
 *
 *   `frozen=True` — responses are immutable server-side, so they are `readonly`
 *   here. Python tuples serialise as JSON arrays, hence `readonly T[]`.
 */

/** Server-side ids are UUIDv7 strings. Branded so a slug cannot be passed
 *  where an id belongs — the two are not interchangeable and the interaction
 *  routes take ids while the article routes take slugs. */
export type Uuid = string & { readonly __brand?: "uuid" };

export type UserId = Uuid;
export type ActorId = Uuid;
export type BlogId = Uuid;
export type CommentId = Uuid;
export type CatalogId = Uuid;
export type PinId = Uuid;
export type SeriesId = Uuid;

/** Lowercase, hyphen-separated: `^[a-z0-9]+(-[a-z0-9]+)*$`. Category keys and
 *  blog slugs share this shape. */
export type KeyStr = string;

/** A heading anchor. Same shape as KeyStr but longer, and may carry a `-2`
 *  disambiguating suffix. Generated by the backend at publish time — never
 *  derive these on the client. */
export type AnchorStr = string;

/** ISO-8601 UTC, e.g. `2026-08-22T12:00:00Z`. One endpoint
 *  (`/auth/otp/request`) emits `+00:00` instead; `parseInstant` handles both. */
export type IsoDateTime = string;

export type ProcessingStage =
  | "AUTH"
  | "ACCESS"
  | "VALIDATE"
  | "PERSIST"
  | "STORAGE"
  | "PUBLISH"
  | "COMPOSE";

export type Retryability = "RETRYABLE" | "NOT_RETRYABLE" | "POLICY_DEPENDENT";

/** The closed set from `ErrorCategory`. The UI branches on these, never on
 *  HTTP status — status is a transport detail and several categories share
 *  one. */
export type ErrorCategory =
  // Auth
  | "AUTH_TOKEN_INVALID"
  | "AUTH_TOKEN_EXPIRED"
  | "AUTH_TOKEN_REVOKED"
  | "AUTH_REQUIRED"
  | "OTP_INVALID"
  | "OTP_EXPIRED"
  | "OTP_ATTEMPTS_EXCEEDED"
  | "OTP_THROTTLED"
  | "OAUTH_PROVIDER_UNKNOWN"
  | "OAUTH_STATE_INVALID"
  | "OAUTH_EXCHANGE_FAILED"
  | "OAUTH_EMAIL_UNVERIFIED"
  | "REFRESH_TOKEN_INVALID"
  | "REFRESH_TOKEN_EXPIRED"
  | "REFRESH_TOKEN_REUSED"
  | "ACTOR_TOKEN_INVALID"
  | "ADMIN_CREDENTIALS_INVALID"
  | "ADMIN_LOCKED_OUT"
  | "ADMIN_PASSWORD_NOT_SET"
  // Access
  | "ACCESS_DENIED"
  | "ADMIN_REQUIRED"
  | "USER_NOT_FOUND"
  | "USER_INACTIVE"
  // Content
  | "BLOG_NOT_FOUND"
  | "BLOG_NOT_PUBLISHED"
  | "SLUG_CONFLICT"
  | "MARKDOWN_INVALID"
  | "MARKDOWN_TOO_LARGE"
  | "SECTION_ANCHOR_UNKNOWN"
  | "SECTION_REFERENCED_BY_PIN"
  | "CATEGORY_UNKNOWN"
  | "SERIES_UNKNOWN"
  // Interaction
  | "COMMENT_NOT_FOUND"
  | "COMMENT_ALREADY_EXISTS"
  | "COMMENT_DEPTH_INVALID"
  | "MARKER_NOT_FOUND"
  | "CATALOG_NOT_FOUND"
  | "CATALOG_NAME_TAKEN"
  | "PIN_NOT_FOUND"
  | "PIN_SELF_REFERENCE"
  // Infrastructure
  | "STORAGE_UNAVAILABLE"
  | "STORAGE_OBJECT_NOT_FOUND"
  | "DATABASE_UNAVAILABLE"
  // Generic
  | "RATE_LIMITED"
  | "REQUEST_INVALID"
  | "INTERNAL_ERROR";

/** Per-field detail attached to `REQUEST_INVALID`. Capped at 10 by the server,
 *  and it never echoes the submitted value. */
export interface FieldViolation {
  readonly field: string;
  readonly reason: string;
}

export interface ErrorEnvelope {
  readonly category: ErrorCategory;
  /** Safe to render verbatim — the server guarantees it leaks nothing. */
  readonly safe_message: string;
  readonly retryability: Retryability;
  readonly stage: ProcessingStage;
  readonly safe_details: Readonly<Record<string, unknown>> & {
    readonly fields?: readonly FieldViolation[];
    readonly reason?: string;
  };
  /** Echoed in the `X-Correlation-ID` header. Show it on error screens: it is
   *  what makes a user's report findable in the server logs. */
  readonly correlation_id: string;
}

/** Every route returns this, success or failure. */
export interface APIResponse<T> {
  readonly success: boolean;
  readonly message: string;
  readonly data: T | null;
  readonly error: ErrorEnvelope | null;
}

/**
 * Keyset pagination. There is no `page`, `offset` or `total` anywhere in this
 * API — the backend refuses OFFSET because it drifts on an append-heavy table.
 *
 * `next_cursor` is an opaque base64url blob. Never parse or construct one.
 */
export interface Page<T> {
  readonly items: readonly T[];
  readonly next_cursor: string | null;
  readonly has_more: boolean;
}
